import { Robot } from './types';

export const MOCK_ROBOTS: Robot[] = [
    {
        id: '1',
        modelName: 'Roborock S8 MaxV Ultra',
        slug: 'roborock-s8-maxv-ultra',
        brandId: 'roborock',
        categoryId: 'robot-vacuums',
        status: 'released',
        mainImage: 'https://m.media-amazon.com/images/I/61pJpBZxmKL._AC_SL1500_.jpg',
        imageGallery: [],
        autonomyScore: 95,
        lowestPrice: 1599.99,
        metaDescription: 'AI-powered obstacle avoidance with ReactiveAI 3.0 and FlexiArm mop design.',
    },
    {
        id: '2',
        modelName: 'Dreame X40 Ultra',
        slug: 'dreame-x40-ultra',
        brandId: 'dreame',
        categoryId: 'robot-vacuums',
        status: 'released',
        mainImage: 'https://m.media-amazon.com/images/I/71rj9wf3f9L._AC_SL1500_.jpg',
        imageGallery: [],
        autonomyScore: 95,
        lowestPrice: 1299.99,
        metaDescription: 'Dual rotating mops with auto-extension for edge and corner cleaning.',
    },
    {
        id: '3',
        modelName: 'Dreame L20 Ultra',
        slug: 'dreame-l20-ultra',
        brandId: 'dreame',
        categoryId: 'robot-vacuums',
        status: 'released',
        mainImage: 'https://m.media-amazon.com/images/I/71K1k1k1k1L._AC_SL1500_.jpg',
        imageGallery: [],
        autonomyScore: 93,
        lowestPrice: 1099.99,
        metaDescription: 'Mop extend technology reaches into corners for thorough edge cleaning.',
    },
    {
        id: '4',
        modelName: 'Roborock S8 Pro Ultra',
        slug: 'roborock-s8-pro-ultra',
        brandId: 'roborock',
        categoryId: 'robot-vacuums',
        status: 'released',
        mainImage: 'https://m.media-amazon.com/images/I/71R2c9-jJBS._AC_SL1500_.jpg',
        imageGallery: [],
        autonomyScore: 92,
        lowestPrice: 1399.99,
        metaDescription: 'The ultimate hands-off cleaning experience with all-in-one base station.',
    },
    {
        id: '5',
        modelName: 'iRobot Roomba j9+',
        slug: 'irobot-roomba-j9-plus',
        brandId: 'irobot',
        categoryId: 'robot-vacuums',
        status: 'released',
        mainImage: 'https://m.media-amazon.com/images/I/71tQsYbKUAL._AC_SL1500_.jpg',
        imageGallery: [],
        autonomyScore: 88,
        lowestPrice: 899.00,
        metaDescription: 'Genius AI-powered robot that recognizes and avoids 80+ types of objects.',
    },
    {
        id: '6',
        modelName: 'iRobot Roomba j7+',
        slug: 'irobot-roomba-j7-plus',
        brandId: 'irobot',
        categoryId: 'robot-vacuums',
        status: 'released',
        mainImage: 'https://m.media-amazon.com/images/I/71eXNMA9XwL._AC_SL1500_.jpg',
        imageGallery: [],
        autonomyScore: 85,
        lowestPrice: 699.00,
        metaDescription: 'Smart mapping and precision obstacle avoidance with P.O.O.P. guarantee.',
    },
    {
        id: '7',
        modelName: 'Ecovacs Deebot X2 Omni',
        slug: 'ecovacs-deebot-x2-omni',
        brandId: 'ecovacs',
        categoryId: 'robot-vacuums',
        status: 'released',
        mainImage: 'https://m.media-amazon.com/images/I/61M4Q1nfzFL._AC_SL1500_.jpg',
        imageGallery: [],
        autonomyScore: 87,
        lowestPrice: 1099.99,
        metaDescription: 'Square design with edge-to-edge brush coverage and hot water mop washing.',
    },
    {
        id: '8',
        modelName: 'Narwal Freo X Ultra',
        slug: 'narwal-freo-x-ultra',
        brandId: 'narwal',
        categoryId: 'robot-vacuums',
        status: 'released',
        mainImage: 'https://m.media-amazon.com/images/I/71WR3TAbmFL._AC_SL1500_.jpg',
        imageGallery: [],
        autonomyScore: 89,
        lowestPrice: 999.00,
        metaDescription: 'Tri-laser navigation and hands-free base station with dirty water tank.',
    },
    {
        id: '9',
        modelName: 'Roborock Q Revo MaxV',
        slug: 'roborock-q-revo-maxv',
        brandId: 'roborock',
        categoryId: 'robot-vacuums',
        status: 'released',
        mainImage: 'https://m.media-amazon.com/images/I/61JJ0Jbj6fL._AC_SL1500_.jpg',
        imageGallery: [],
        autonomyScore: 90,
        lowestPrice: 799.99,
        metaDescription: 'ReactiveAI 2.0 obstacle avoidance in a more affordable package.',
    },
    {
        id: '10',
        modelName: 'Shark Matrix Robot Vacuum',
        slug: 'shark-matrix-robot-vacuum',
        brandId: 'shark',
        categoryId: 'robot-vacuums',
        status: 'released',
        mainImage: 'https://m.media-amazon.com/images/I/71DkJPiHT1L._AC_SL1500_.jpg',
        imageGallery: [],
        autonomyScore: 78,
        lowestPrice: 349.99,
        metaDescription: 'Matrix Clean home mapping with sonic mopping for multi-surface floors.',
    },
    {
        id: '11',
        modelName: 'Eufy RoboVac X10 Pro Omni',
        slug: 'eufy-robovac-x10-pro-omni',
        brandId: 'eufy',
        categoryId: 'robot-vacuums',
        status: 'released',
        mainImage: 'https://m.media-amazon.com/images/I/71Q7F-nVAFL._AC_SL1500_.jpg',
        imageGallery: [],
        autonomyScore: 84,
        lowestPrice: 699.99,
        metaDescription: '8000Pa suction with AI-powered dynamic obstacle avoidance.',
    },
    {
        id: '12',
        modelName: 'iRobot Roomba Combo j9+',
        slug: 'irobot-roomba-combo-j9-plus',
        brandId: 'irobot',
        categoryId: 'robot-vacuums',
        status: 'released',
        mainImage: 'https://m.media-amazon.com/images/I/71GVqKb2jIL._AC_SL1500_.jpg',
        imageGallery: [],
        autonomyScore: 86,
        lowestPrice: 999.99,
        metaDescription: 'Retractable mop head that automatically lifts on carpets.',
    },
    {
        id: '13',
        modelName: 'Roborock S8',
        slug: 'roborock-s8',
        brandId: 'roborock',
        categoryId: 'robot-vacuums',
        status: 'released',
        mainImage: 'https://m.media-amazon.com/images/I/71C5QQG7OkL._AC_SL1500_.jpg',
        imageGallery: [],
        autonomyScore: 88,
        lowestPrice: 549.99,
        metaDescription: 'Dual rubber brushes with sonic mopping at 3000 scrubs per minute.',
    },
];
